# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python CI

on:
  push:
    branches: 
        - main
  pull_request:
    branches:
        - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
        #check out the code from the repository
      - name: Check out code
      - uses: actions/checkout@v4

        #set up python environment
      - name: Set up Python 3.12
        uses: actions/setup-python@v3
        with:
            python-version: "3.12"
            
        #install dependencies
      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install flake8 pytest
        
        #run tests
      - name: Test with pytest
        run: pytest
